In [2]:
import pandas as pd

products = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\warehouse_restock_prediction\data\raw_data\Inventory.csv")

warehouses = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\warehouse_restock_prediction\data\raw_data\Warehouses.csv")

sales = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\warehouse_restock_prediction\data\raw_data\Sales_History.csv")

inventory = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\warehouse_restock_prediction\data\raw_data\Inventory.csv")

In [3]:
print("products")
print(products.head())
print("#######################")
print("warehouse")
print(warehouses.head())
print("#######################")
print("sales")
print(sales.head())
print("#######################")
print("inventory")
print(inventory.head())

products
   hub_id product_id  current_stock last_updated
0  HUB001    P000001            216   2025-12-31
1  HUB001    P000002            808   2025-12-31
2  HUB001    P000003            418   2025-12-31
3  HUB001    P000004            431   2025-12-31
4  HUB001    P000005            205   2025-12-31
#######################
warehouse
   hub_id       hub_name       city
0  HUB001    Chennai Hub    Chennai
1  HUB002  Bengaluru Hub  Bengaluru
2  HUB003  Hyderabad Hub  Hyderabad
3  HUB004     Mumbai Hub     Mumbai
4  HUB005      Delhi Hub      Delhi
#######################
sales
   year  month  hub_id product_id  opening_stock  quantity_sold  promotion  \
0  2023      1  HUB001    P000001            527            132          0
1  2023      1  HUB001    P000002            506             50          0
2  2023      1  HUB001    P000003            427            111          0
3  2023      1  HUB001    P000004            531             77          0
4  2023      1  HUB001    P000005            855             28          0

   discount_percentage  festival_flag  returns  closing_stock
0                    0              1        6            401
1                    0              1        0            456
2                    0              1        2            318
3                    0              1        3            457
4                    0              1        1            828
#######################
inventory
   hub_id product_id  current_stock last_updated
0  HUB001    P000001            216   2025-12-31
1  HUB001    P000002            808   2025-12-31
2  HUB001    P000003            418   2025-12-31
3  HUB001    P000004            431   2025-12-31
4  HUB001    P000005            205   2025-12-31

In [4]:
df = warehouses.merge(
    products,
    on="hub_id",
    how="left"
)
df

,hub_id,hub_name,city,product_id,current_stock,last_updated
0,HUB001,Chennai Hub,Chennai,P000001,216,2025-12-31
1,HUB001,Chennai Hub,Chennai,P000002,808,2025-12-31
2,HUB001,Chennai Hub,Chennai,P000003,418,2025-12-31
3,HUB001,Chennai Hub,Chennai,P000004,431,2025-12-31
4,HUB001,Chennai Hub,Chennai,P000005,205,2025-12-31
...,...,...,...,...,...,...
4995,HUB010,Coimbatore Hub,Coimbatore,P000496,255,2025-12-31
4996,HUB010,Coimbatore Hub,Coimbatore,P000497,189,2025-12-31
4997,HUB010,Coimbatore Hub,Coimbatore,P000498,570,2025-12-31
4998,HUB010,Coimbatore Hub,Coimbatore,P000499,225,2025-12-31
4999,HUB010,Coimbatore Hub,Coimbatore,P000500,683,2025-12-31

In [5]:
df = sales.merge(
    products,
    on="product_id",
    how="left"
)

In [6]:
print(df.columns.tolist())
print(warehouses.columns.tolist())

['year', 'month', 'hub_id_x', 'product_id', 'opening_stock', 'quantity_sold', 'promotion', 'discount_percentage', 'festival_flag', 'returns', 'closing_stock', 'hub_id_y', 'current_stock', 'last_updated']
['hub_id', 'hub_name', 'city']

In [7]:
df = sales.merge(
    products,
    on="product_id",
    how="left"
)

In [8]:
print(df.columns)

Index(['year', 'month', 'hub_id_x', 'product_id', 'opening_stock',
       'quantity_sold', 'promotion', 'discount_percentage', 'festival_flag',
       'returns', 'closing_stock', 'hub_id_y', 'current_stock',
       'last_updated'],
      dtype='str')

In [9]:
df = df.drop(columns=["hub_id_y"])

In [10]:
df

,year,month,hub_id_x,product_id,opening_stock,quantity_sold,promotion,discount_percentage,festival_flag,returns,closing_stock,current_stock,last_updated
0,2023,1,HUB001,P000001,527,132,0,0,1,6,401,216,2025-12-31
1,2023,1,HUB001,P000001,527,132,0,0,1,6,401,463,2025-12-31
2,2023,1,HUB001,P000001,527,132,0,0,1,6,401,512,2025-12-31
3,2023,1,HUB001,P000001,527,132,0,0,1,6,401,376,2025-12-31
4,2023,1,HUB001,P000001,527,132,0,0,1,6,401,440,2025-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799995,2025,12,HUB010,P000500,736,55,0,0,1,2,683,457,2025-12-31
1799996,2025,12,HUB010,P000500,736,55,0,0,1,2,683,343,2025-12-31
1799997,2025,12,HUB010,P000500,736,55,0,0,1,2,683,200,2025-12-31
1799998,2025,12,HUB010,P000500,736,55,0,0,1,2,683,383,2025-12-31
1799999,2025,12,HUB010,P000500,736,55,0,0,1,2,683,683,2025-12-31

In [11]:
df = df.rename(columns={
    "hub_id_x": "hub_id"
})

In [12]:
df = df.merge(
    warehouses,
    on="hub_id",
    how="left"
)

In [13]:
df.columns

Index(['year', 'month', 'hub_id', 'product_id', 'opening_stock',
       'quantity_sold', 'promotion', 'discount_percentage', 'festival_flag',
       'returns', 'closing_stock', 'current_stock', 'last_updated', 'hub_name',
       'city'],
      dtype='str')

In [14]:
df = df.sort_values(
    by=["product_id", "hub_id", "year", "month"]
).reset_index(drop=True)

In [15]:
df

,year,month,hub_id,product_id,opening_stock,quantity_sold,promotion,discount_percentage,festival_flag,returns,closing_stock,current_stock,last_updated,hub_name,city
0,2023,1,HUB001,P000001,527,132,0,0,1,6,401,216,2025-12-31,Chennai Hub,Chennai
1,2023,1,HUB001,P000001,527,132,0,0,1,6,401,463,2025-12-31,Chennai Hub,Chennai
2,2023,1,HUB001,P000001,527,132,0,0,1,6,401,512,2025-12-31,Chennai Hub,Chennai
3,2023,1,HUB001,P000001,527,132,0,0,1,6,401,376,2025-12-31,Chennai Hub,Chennai
4,2023,1,HUB001,P000001,527,132,0,0,1,6,401,440,2025-12-31,Chennai Hub,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799995,2025,12,HUB010,P000500,736,55,0,0,1,2,683,457,2025-12-31,Coimbatore Hub,Coimbatore
1799996,2025,12,HUB010,P000500,736,55,0,0,1,2,683,343,2025-12-31,Coimbatore Hub,Coimbatore
1799997,2025,12,HUB010,P000500,736,55,0,0,1,2,683,200,2025-12-31,Coimbatore Hub,Coimbatore
1799998,2025,12,HUB010,P000500,736,55,0,0,1,2,683,383,2025-12-31,Coimbatore Hub,Coimbatore
1799999,2025,12,HUB010,P000500,736,55,0,0,1,2,683,683,2025-12-31,Coimbatore Hub,Coimbatore

In [16]:
group = df.groupby(
    ["product_id", "hub_id"]
)

In [17]:
group

In [18]:
df["sales_last_1"] = group["quantity_sold"].shift(1)

df["sales_last_2"] = group["quantity_sold"].shift(2)

df["sales_last_3"] = group["quantity_sold"].shift(3)

In [19]:
df["avg_sales_3"] = df[
    [
        "sales_last_1",
        "sales_last_2",
        "sales_last_3"
    ]
].mean(axis=1)

In [20]:
df["target_next_month_demand"] = (
    group["quantity_sold"]
    .shift(-1)
)

In [21]:
df = df.dropna().reset_index(drop=True)

In [22]:
df

,year,month,hub_id,product_id,opening_stock,quantity_sold,promotion,discount_percentage,festival_flag,returns,closing_stock,current_stock,last_updated,hub_name,city,sales_last_1,sales_last_2,sales_last_3,avg_sales_3,target_next_month_demand
0,2023,1,HUB001,P000001,527,132,0,0,1,6,401,376,2025-12-31,Chennai Hub,Chennai,132.0,132.0,132.0,132.0,132.0
1,2023,1,HUB001,P000001,527,132,0,0,1,6,401,440,2025-12-31,Chennai Hub,Chennai,132.0,132.0,132.0,132.0,132.0
2,2023,1,HUB001,P000001,527,132,0,0,1,6,401,775,2025-12-31,Chennai Hub,Chennai,132.0,132.0,132.0,132.0,132.0
3,2023,1,HUB001,P000001,527,132,0,0,1,6,401,539,2025-12-31,Chennai Hub,Chennai,132.0,132.0,132.0,132.0,132.0
4,2023,1,HUB001,P000001,527,132,0,0,1,6,401,567,2025-12-31,Chennai Hub,Chennai,132.0,132.0,132.0,132.0,132.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779995,2025,12,HUB010,P000500,736,55,0,0,1,2,683,683,2025-12-31,Coimbatore Hub,Coimbatore,55.0,55.0,55.0,55.0,55.0
1779996,2025,12,HUB010,P000500,736,55,0,0,1,2,683,457,2025-12-31,Coimbatore Hub,Coimbatore,55.0,55.0,55.0,55.0,55.0
1779997,2025,12,HUB010,P000500,736,55,0,0,1,2,683,343,2025-12-31,Coimbatore Hub,Coimbatore,55.0,55.0,55.0,55.0,55.0
1779998,2025,12,HUB010,P000500,736,55,0,0,1,2,683,200,2025-12-31,Coimbatore Hub,Coimbatore,55.0,55.0,55.0,55.0,55.0
1779999,2025,12,HUB010,P000500,736,55,0,0,1,2,683,383,2025-12-31,Coimbatore Hub,Coimbatore,55.0,55.0,55.0,55.0,55.0

In [23]:
training_df = df[
    [
        "product_id",
        "hub_id",
        "year",
        "month",
        "current_stock",
        "sales_last_1",
        "sales_last_2",
        "sales_last_3",
        "avg_sales_3",
        "promotion",
        "festival_flag",
        "discount_percentage",
        "returns",
        "target_next_month_demand",
    ]
]

In [24]:
training_df

,product_id,hub_id,year,month,current_stock,sales_last_1,sales_last_2,sales_last_3,avg_sales_3,promotion,festival_flag,discount_percentage,returns,target_next_month_demand
0,P000001,HUB001,2023,1,376,132.0,132.0,132.0,132.0,0,1,0,6,132.0
1,P000001,HUB001,2023,1,440,132.0,132.0,132.0,132.0,0,1,0,6,132.0
2,P000001,HUB001,2023,1,775,132.0,132.0,132.0,132.0,0,1,0,6,132.0
3,P000001,HUB001,2023,1,539,132.0,132.0,132.0,132.0,0,1,0,6,132.0
4,P000001,HUB001,2023,1,567,132.0,132.0,132.0,132.0,0,1,0,6,132.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779995,P000500,HUB010,2025,12,683,55.0,55.0,55.0,55.0,0,1,0,2,55.0
1779996,P000500,HUB010,2025,12,457,55.0,55.0,55.0,55.0,0,1,0,2,55.0
1779997,P000500,HUB010,2025,12,343,55.0,55.0,55.0,55.0,0,1,0,2,55.0
1779998,P000500,HUB010,2025,12,200,55.0,55.0,55.0,55.0,0,1,0,2,55.0
1779999,P000500,HUB010,2025,12,383,55.0,55.0,55.0,55.0,0,1,0,2,55.0

In [25]:
print(training_df.head())

print(training_df.shape)

print(training_df.isnull().sum())

  product_id  hub_id  year  month  current_stock  sales_last_1  sales_last_2  \
0    P000001  HUB001  2023      1            376         132.0         132.0
1    P000001  HUB001  2023      1            440         132.0         132.0
2    P000001  HUB001  2023      1            775         132.0         132.0
3    P000001  HUB001  2023      1            539         132.0         132.0
4    P000001  HUB001  2023      1            567         132.0         132.0

   sales_last_3  avg_sales_3  promotion  festival_flag  discount_percentage  \
0         132.0        132.0          0              1                    0
1         132.0        132.0          0              1                    0
2         132.0        132.0          0              1                    0
3         132.0        132.0          0              1                    0
4         132.0        132.0          0              1                    0

   returns  target_next_month_demand
0        6                     132.0
1        6                     132.0
2        6                     132.0
3        6                     132.0
4        6                     132.0
(1780000, 14)
product_id                  0
hub_id                      0
year                        0
month                       0
current_stock               0
sales_last_1                0
sales_last_2                0
sales_last_3                0
avg_sales_3                 0
promotion                   0
festival_flag               0
discount_percentage         0
returns                     0
target_next_month_demand    0
dtype: int64

In [26]:
training_df["date"] = pd.to_datetime(
    training_df["year"].astype(str)
    + "-"
    + training_df["month"].astype(str)
    + "-01"
)

In [27]:
train_df = training_df[
    training_df["date"] < "2025-01-01"
]

In [28]:
val_df = training_df[
    (training_df["date"] >= "2025-01-01") &
    (training_df["date"] < "2025-07-01")
]

In [29]:
test_df = training_df[
    training_df["date"] >= "2025-07-01"
]

In [30]:
X_train = train_df.drop(
    columns=["target_next_month_demand", "date"]
)

y_train = train_df["target_next_month_demand"]

In [31]:
X_val = val_df.drop(
    columns=["target_next_month_demand", "date"]
)

y_val = val_df["target_next_month_demand"]

In [32]:
X_test = test_df.drop(
    columns=["target_next_month_demand", "date"]
)

y_test = test_df["target_next_month_demand"]

In [33]:
print("Train :", X_train.shape)
print("Validation :", X_val.shape)
print("Test :", X_test.shape)

Train : (1185000, 13)
Validation : (300000, 13)
Test : (295000, 13)

In [34]:
from catboost import CatBoostRegressor

cat_features = ["product_id", "hub_id"]

model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    random_seed=42,
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    use_best_model=True
)

0:	learn: 35.1016058	test: 32.7635214	best: 32.7635214 (0)	total: 1.84s	remaining: 30m 43s
100:	learn: 7.3844855	test: 7.0101536	best: 7.0101536 (100)	total: 2m 40s	remaining: 23m 49s
200:	learn: 7.1237954	test: 6.7355810	best: 6.7355810 (200)	total: 4m 41s	remaining: 18m 40s
300:	learn: 7.0106865	test: 6.6179104	best: 6.6179104 (300)	total: 6m 46s	remaining: 15m 43s
400:	learn: 6.9366888	test: 6.5540523	best: 6.5540523 (400)	total: 8m 47s	remaining: 13m 7s
500:	learn: 6.8816376	test: 6.5052016	best: 6.5052016 (500)	total: 10m 39s	remaining: 10m 37s
600:	learn: 6.8485576	test: 6.4749052	best: 6.4749052 (600)	total: 12m 35s	remaining: 8m 21s
700:	learn: 6.8158020	test: 6.4451924	best: 6.4451924 (700)	total: 14m 30s	remaining: 6m 11s
800:	learn: 6.7814208	test: 6.4173128	best: 6.4173128 (800)	total: 16m 27s	remaining: 4m 5s
900:	learn: 6.7549933	test: 6.3949010	best: 6.3949010 (900)	total: 18m 13s	remaining: 2m
999:	learn: 6.7259379	test: 6.3723226	best: 6.3723226 (999)	total: 19m 57s	remaining: 0us

bestTest = 6.372322596
bestIteration = 999

CatBoostRegressor(depth=8, iterations=1000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [35]:
y_pred = model.predict(X_test)

In [36]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)
print("MAPE:", mape)

MAE : 3.7315734742517157
RMSE: 6.954474013735637
R²  : 0.9679996414965216
MAPE: 4.622720000795531

In [37]:
feature_importance = model.get_feature_importance()

importance_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": feature_importance
}).sort_values("Importance", ascending=False)

print(importance_df)

                Feature  Importance
5          sales_last_1   66.030418
6          sales_last_2    9.387881
8           avg_sales_3    7.035854
0            product_id    4.605383
3                 month    3.636133
7          sales_last_3    3.179661
10        festival_flag    2.607674
1                hub_id    1.472120
12              returns    1.384374
4         current_stock    0.648046
2                  year    0.006057
11  discount_percentage    0.004156
9             promotion    0.002245

In [39]:
import joblib

joblib.dump(
    model,
    "catboost_inventory.pkl"
)

['catboost_inventory.pkl']

In [48]:
import joblib

model = joblib.load("catboost_inventory.pkl")

In [38]:

product_id = "P000500"
hub_id = "HUB010"

inventory_row = inventory[
    (inventory["product_id"] == product_id) &
    (inventory["hub_id"] == hub_id)
]

current_stock = inventory_row.iloc[0]["current_stock"]

print(current_stock)

683

In [40]:
sales_row = sales[
    (sales["product_id"] == product_id) &
    (sales["hub_id"] == hub_id)
]

In [41]:
sales_row = sales_row.sort_values(
    ["year", "month"]
)

In [43]:
last_3 = sales_row.tail(3)

print(last_3)

        year  month  hub_id product_id  opening_stock  quantity_sold  \
169999  2025     10  HUB010    P000500            223             51
174999  2025     11  HUB010    P000500            802             68
179999  2025     12  HUB010    P000500            736             55

        promotion  discount_percentage  festival_flag  returns  closing_stock
169999          0                    0              1        1            802
174999          0                    0              1        2            736
179999          0                    0              1        2            683

In [44]:
sales_last_1 = last_3.iloc[2]["quantity_sold"]   # December
sales_last_2 = last_3.iloc[1]["quantity_sold"]   # November
sales_last_3 = last_3.iloc[0]["quantity_sold"]   # October

avg_sales_3 = (
    sales_last_1 +
    sales_last_2 +
    sales_last_3
) / 3

In [45]:
print(sales_last_1)
print(sales_last_2)
print(sales_last_3)
print(avg_sales_3)

55
68
51
58.0

In [49]:
input_df = pd.DataFrame({
    "product_id": ["P000500"],
    "hub_id": ["HUB010"],
    "year": [2026],
    "month": [1],
    "current_stock": [current_stock],
    "sales_last_1": [sales_last_1],
    "sales_last_2": [sales_last_2],
    "sales_last_3": [sales_last_3],
    "avg_sales_3": [avg_sales_3],
    "promotion": [0],
    "festival_flag": [0],
    "discount_percentage": [0],
    "returns": [5]
})

In [50]:
predicted_demand = model.predict(input_df)[0]

print(predicted_demand)

74.35990649414204

In [51]:
remaining_stock = current_stock - predicted_demand

restock_required = remaining_stock < 0

safety_stock = 40

recommended_restock_quantity = max(
    0,
    predicted_demand + safety_stock - current_stock
)

In [52]:
response = {
    "product_id": "P000500",
    "hub_id": "HUB010",
    "current_stock": current_stock,
    "predicted_demand": round(predicted_demand),
    "remaining_stock": round(remaining_stock),
    "restock_required": restock_required,
    "recommended_restock_quantity": round(recommended_restock_quantity)
}

print(response)

{'product_id': 'P000500', 'hub_id': 'HUB010', 'current_stock': np.int64(683), 'predicted_demand': 74, 'remaining_stock': 609, 'restock_required': np.False_, 'recommended_restock_quantity': 0}