In [11]:
from pathlib import Path

import warnings

import polars as pl

warnings.filterwarnings("ignore")

pl.Config.set_tbl_rows(10)
pl.Config.set_tbl_cols(20)

polars.config.Config

In [12]:
PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"

INTERIM_DIR = PROJECT_ROOT / "data" / "interim"

INTERIM_DIR.mkdir(parents=True, exist_ok=True)

In [13]:
products_df = pl.read_csv(RAW_DIR / "Products.csv")

warehouses_df = pl.read_csv(RAW_DIR / "Warehouses.csv")

sales_df = pl.read_csv(RAW_DIR / "Sales_History.csv")

inventory_df = pl.read_csv(RAW_DIR / "Inventory.csv")

In [14]:
required_sales_columns = [
    "product_id",
    "hub_id",
    "year",
    "month",
]

missing = [
    col
    for col in required_sales_columns
    if col not in sales_df.columns
]

assert len(missing) == 0, f"Missing columns: {missing}"

print("Sales schema validated.")

Sales schema validated.

In [15]:
sales_df = sales_df.with_columns(
    [
        pl.col("year").cast(pl.Int16),
        pl.col("month").cast(pl.Int8),
        pl.col("promotion").cast(pl.Int8),
        pl.col("festival_flag").cast(pl.Int8),
    ]
)

In [16]:
merged_df = (
    sales_df
    .join(
        products_df,
        on="product_id",
        how="left",
    )
    .join(
        warehouses_df,
        on="hub_id",
        how="left",
    )
    .join(
        inventory_df,
        on=["hub_id", "product_id"],
        how="left",
    )
)

In [17]:
print(merged_df.shape)

display(merged_df.head())

display(merged_df.null_count())

(180000, 19)

shape: (5, 19)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ yea ┆ mon ┆ hub ┆ pro ┆ ope ┆ qua ┆ pro ┆ dis ┆ fes ┆ ret ┆ clo ┆ pro ┆ sku ┆ cat ┆ bra ┆ hub ┆ cit ┆ cur ┆ las │
│ r   ┆ th  ┆ _id ┆ duc ┆ nin ┆ nti ┆ mot ┆ cou ┆ tiv ┆ urn ┆ sin ┆ duc ┆ --- ┆ ego ┆ nd  ┆ _na ┆ y   ┆ ren ┆ t_u │
│ --- ┆ --- ┆ --- ┆ t_i ┆ g_s ┆ ty_ ┆ ion ┆ nt_ ┆ al_ ┆ s   ┆ g_s ┆ t_n ┆ str ┆ ry  ┆ --- ┆ me  ┆ --- ┆ t_s ┆ pda │
│ i16 ┆ i8  ┆ str ┆ d   ┆ toc ┆ sol ┆ --- ┆ per ┆ fla ┆ --- ┆ toc ┆ ame ┆     ┆ --- ┆ str ┆ --- ┆ str ┆ toc ┆ ted │
│     ┆     ┆     ┆ --- ┆ k   ┆ d   ┆ i8  ┆ cen ┆ g   ┆ i64 ┆ k   ┆ --- ┆     ┆ str ┆     ┆ str ┆     ┆ k   ┆ --- │
│     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ tag ┆ --- ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ e   ┆ i8  ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 1   ┆ HUB ┆ P00 ┆ 527 ┆ 132 ┆ 0   ┆ 0   ┆ 1   ┆ 6   ┆ 401 ┆ App ┆ SKU ┆ Fas ┆ App ┆ Che ┆ Che ┆ 216 ┆ 202 │
│ 3   ┆     ┆ 001 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆ 000 ┆ hio ┆ le  ┆ nna ┆ nna ┆     ┆ 5-1 │
│     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fas ┆ 01  ┆ n   ┆     ┆ i   ┆ i   ┆     ┆ 2-3 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hio ┆     ┆     ┆     ┆ Hub ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n 1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 1   ┆ HUB ┆ P00 ┆ 506 ┆ 50  ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 456 ┆ LG  ┆ SKU ┆ Spo ┆ LG  ┆ Che ┆ Che ┆ 808 ┆ 202 │
│ 3   ┆     ┆ 001 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Spo ┆ 000 ┆ rts ┆     ┆ nna ┆ nna ┆     ┆ 5-1 │
│     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rts ┆ 02  ┆     ┆     ┆ i   ┆ i   ┆     ┆ 2-3 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ Hub ┆     ┆     ┆ 1   │
│ 202 ┆ 1   ┆ HUB ┆ P00 ┆ 427 ┆ 111 ┆ 0   ┆ 0   ┆ 1   ┆ 2   ┆ 318 ┆ Sam ┆ SKU ┆ Hom ┆ Sam ┆ Che ┆ Che ┆ 418 ┆ 202 │
│ 3   ┆     ┆ 001 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sun ┆ 000 ┆ e   ┆ sun ┆ nna ┆ nna ┆     ┆ 5-1 │
│     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆ 03  ┆     ┆ g   ┆ i   ┆ i   ┆     ┆ 2-3 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆ Hub ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e 3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 1   ┆ HUB ┆ P00 ┆ 531 ┆ 77  ┆ 0   ┆ 0   ┆ 1   ┆ 3   ┆ 457 ┆ Pum ┆ SKU ┆ Fas ┆ Pum ┆ Che ┆ Che ┆ 431 ┆ 202 │
│ 3   ┆     ┆ 001 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆ 000 ┆ hio ┆ a   ┆ nna ┆ nna ┆     ┆ 5-1 │
│     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fas ┆ 04  ┆ n   ┆     ┆ i   ┆ i   ┆     ┆ 2-3 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hio ┆     ┆     ┆     ┆ Hub ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n 4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 1   ┆ HUB ┆ P00 ┆ 855 ┆ 28  ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 828 ┆ App ┆ SKU ┆ Ele ┆ App ┆ Che ┆ Che ┆ 205 ┆ 202 │
│ 3   ┆     ┆ 001 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆ 000 ┆ ctr ┆ le  ┆ nna ┆ nna ┆     ┆ 5-1 │
│     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ele ┆ 05  ┆ oni ┆     ┆ i   ┆ i   ┆     ┆ 2-3 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctr ┆     ┆ cs  ┆     ┆ Hub ┆     ┆     ┆ 1   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oni ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

shape: (1, 19)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ yea ┆ mon ┆ hub ┆ pro ┆ ope ┆ qua ┆ pro ┆ dis ┆ fes ┆ ret ┆ clo ┆ pro ┆ sku ┆ cat ┆ bra ┆ hub ┆ cit ┆ cur ┆ las │
│ r   ┆ th  ┆ _id ┆ duc ┆ nin ┆ nti ┆ mot ┆ cou ┆ tiv ┆ urn ┆ sin ┆ duc ┆ --- ┆ ego ┆ nd  ┆ _na ┆ y   ┆ ren ┆ t_u │
│ --- ┆ --- ┆ --- ┆ t_i ┆ g_s ┆ ty_ ┆ ion ┆ nt_ ┆ al_ ┆ s   ┆ g_s ┆ t_n ┆ u32 ┆ ry  ┆ --- ┆ me  ┆ --- ┆ t_s ┆ pda │
│ u32 ┆ u32 ┆ u32 ┆ d   ┆ toc ┆ sol ┆ --- ┆ per ┆ fla ┆ --- ┆ toc ┆ ame ┆     ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ toc ┆ ted │
│     ┆     ┆     ┆ --- ┆ k   ┆ d   ┆ u32 ┆ cen ┆ g   ┆ u32 ┆ k   ┆ --- ┆     ┆ u32 ┆     ┆ u32 ┆     ┆ k   ┆ --- │
│     ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆ tag ┆ --- ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 │
│     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆ e   ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [18]:
merged_df.write_parquet(
    INTERIM_DIR / "merged.parquet"
)

print("Merged dataset saved successfully.")

Merged dataset saved successfully.